add_test([=[BoardTest.InitialState]=]  /Users/karrics/Projects/Tetris_1/build/TetrisTests [==[--gtest_filter=BoardTest.InitialState]==] --gtest_also_run_disabled_tests)
set_tests_properties([=[BoardTest.InitialState]=]  PROPERTIES WORKING_DIRECTORY /Users/karrics/Projects/Tetris_1/build SKIP_REGULAR_EXPRESSION [==[\[  SKIPPED \]]==])
add_test([=[BoardTest.CollisionOutOfBounds]=]  /Users/karrics/Projects/Tetris_1/build/TetrisTests [==[--gtest_filter=BoardTest.CollisionOutOfBounds]==] --gtest_also_run_disabled_tests)
set_tests_properties([=[BoardTest.CollisionOutOfBounds]=]  PROPERTIES WORKING_DIRECTORY /Users/karrics/Projects/Tetris_1/build SKIP_REGULAR_EXPRESSION [==[\[  SKIPPED \]]==])
add_test([=[BoardTest.ClearLines]=]  /Users/karrics/Projects/Tetris_1/build/TetrisTests [==[--gtest_filter=BoardTest.ClearLines]==] --gtest_also_run_disabled_tests)
set_tests_properties([=[BoardTest.ClearLines]=]  PROPERTIES WORKING_DIRECTORY /Users/karrics/Projects/Tetris_1/build SKIP_REGULAR_EXPRESSION [==[\[  SKIPPED \]]==])
add_test([=[BoardTest.GameOver]=]  /Users/karrics/Projects/Tetris_1/build/TetrisTests [==[--gtest_filter=BoardTest.GameOver]==] --gtest_also_run_disabled_tests)
set_tests_properties([=[BoardTest.GameOver]=]  PROPERTIES WORKING_DIRECTORY /Users/karrics/Projects/Tetris_1/build SKIP_REGULAR_EXPRESSION [==[\[  SKIPPED \]]==])
set(  TetrisTests_TESTS BoardTest.InitialState BoardTest.CollisionOutOfBounds BoardTest.ClearLines BoardTest.GameOver)
